--
-- PostgreSQL database cluster dump
--

-- Started on 2025-02-26 15:55:11 CET

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;
CREATE ROLE turnonauta;
ALTER ROLE turnonauta WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:TKkxSCDOA4H26t/YX2uBwg==$KZB/KF0ihqp+odQtkip7/Ai2lQ1tMNWd5sdKWB9sf5A=:4QNERSk5e9Dd1NsCEElc6n7Df6WXro+ch/PBwseKvsU=';


--
-- Role memberships
--

GRANT pg_read_all_data TO turnonauta GRANTED BY postgres;
GRANT pg_read_all_settings TO turnonauta GRANTED BY postgres;
GRANT pg_read_all_stats TO turnonauta GRANTED BY postgres;




--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

-- Started on 2025-02-26 15:55:11 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-02-26 15:55:11 CET

--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

-- Started on 2025-02-26 15:55:11 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Completed on 2025-02-26 15:55:11 CET

--
-- PostgreSQL database dump complete
--

--
-- Database "turnonauta" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.15 (Ubuntu 14.15-0ubuntu0.22.04.1)

-- Started on 2025-02-26 15:55:11 CET

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3475 (class 1262 OID 16384)
-- Name: turnonauta; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE turnonauta WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'ca_ES.UTF-8';


ALTER DATABASE turnonauta OWNER TO postgres;

\connect turnonauta

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 16385)
-- Name: emparellaments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.emparellaments (
    id_emparellant integer NOT NULL,
    id_usuari1 integer,
    id_usuari2 integer
);


ALTER TABLE public.emparellaments OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16388)
-- Name: emparellaments_id_emparellant_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.emparellaments_id_emparellant_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.emparellaments_id_emparellant_seq OWNER TO postgres;

--
-- TOC entry 3477 (class 0 OID 0)
-- Dependencies: 210
-- Name: emparellaments_id_emparellant_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.emparellaments_id_emparellant_seq OWNED BY public.emparellaments.id_emparellant;


--
-- TOC entry 211 (class 1259 OID 16389)
-- Name: estadistiques; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estadistiques (
    id_estats integer NOT NULL,
    partides_jugades integer DEFAULT 0,
    partides_guanyades integer DEFAULT 0,
    punts_totals integer DEFAULT 0
);


ALTER TABLE public.estadistiques OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16395)
-- Name: estadistiques_id_estats_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.estadistiques_id_estats_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.estadistiques_id_estats_seq OWNER TO postgres;

--
-- TOC entry 3478 (class 0 OID 0)
-- Dependencies: 212
-- Name: estadistiques_id_estats_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.estadistiques_id_estats_seq OWNED BY public.estadistiques.id_estats;


--
-- TOC entry 213 (class 1259 OID 16396)
-- Name: format; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.format (
    id_format integer NOT NULL,
    nom character varying(100) NOT NULL,
    joc character varying(100) NOT NULL,
    jugadors integer NOT NULL,
    temps integer,
    regles text
);


ALTER TABLE public.format OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16401)
-- Name: format_id_format_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.format_id_format_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.format_id_format_seq OWNER TO postgres;

--
-- TOC entry 3479 (class 0 OID 0)
-- Dependencies: 214
-- Name: format_id_format_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.format_id_format_seq OWNED BY public.format.id_format;


--
-- TOC entry 215 (class 1259 OID 16402)
-- Name: partida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partida (
    id_partida integer NOT NULL,
    data_inici timestamp without time zone NOT NULL,
    estat character varying(50) NOT NULL,
    id_emparellant integer
);


ALTER TABLE public.partida OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 16405)
-- Name: partida_id_partida_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.partida_id_partida_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.partida_id_partida_seq OWNER TO postgres;

--
-- TOC entry 3480 (class 0 OID 0)
-- Dependencies: 216
-- Name: partida_id_partida_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.partida_id_partida_seq OWNED BY public.partida.id_partida;


--
-- TOC entry 217 (class 1259 OID 16406)
-- Name: rang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rang (
    id_rang integer NOT NULL,
    nom character varying(50) NOT NULL,
    descripcio text
);


ALTER TABLE public.rang OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16411)
-- Name: rang_id_rang_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rang_id_rang_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.rang_id_rang_seq OWNER TO postgres;

--
-- TOC entry 3481 (class 0 OID 0)
-- Dependencies: 218
-- Name: rang_id_rang_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rang_id_rang_seq OWNED BY public.rang.id_rang;


--
-- TOC entry 219 (class 1259 OID 16412)
-- Name: resultat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resultat (
    id_resultat integer NOT NULL,
    joc character varying(100) NOT NULL,
    resultat text NOT NULL
);


ALTER TABLE public.resultat OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16417)
-- Name: resultat_id_resultat_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.resultat_id_resultat_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.resultat_id_resultat_seq OWNER TO postgres;

--
-- TOC entry 3482 (class 0 OID 0)
-- Dependencies: 220
-- Name: resultat_id_resultat_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.resultat_id_resultat_seq OWNED BY public.resultat.id_resultat;


--
-- TOC entry 221 (class 1259 OID 16418)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id_rol integer NOT NULL,
    nom character varying(50) NOT NULL,
    permet_torneig boolean NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16421)
-- Name: rol_id_rol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rol_id_rol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.rol_id_rol_seq OWNER TO postgres;

--
-- TOC entry 3483 (class 0 OID 0)
-- Dependencies: 222
-- Name: rol_id_rol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rol_id_rol_seq OWNED BY public.rol.id_rol;


--
-- TOC entry 223 (class 1259 OID 16422)
-- Name: subscripcio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscripcio (
    id_subscripcio integer NOT NULL,
    data_inici date NOT NULL,
    data_final date,
    tipus character varying(50) NOT NULL,
    estat character varying(20) NOT NULL
);


ALTER TABLE public.subscripcio OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16425)
-- Name: subscripcio_id_subscripcio_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.subscripcio_id_subscripcio_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.subscripcio_id_subscripcio_seq OWNER TO postgres;

--
-- TOC entry 3484 (class 0 OID 0)
-- Dependencies: 224
-- Name: subscripcio_id_subscripcio_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.subscripcio_id_subscripcio_seq OWNED BY public.subscripcio.id_subscripcio;


--
-- TOC entry 225 (class 1259 OID 16426)
-- Name: torneig; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.torneig (
    id integer NOT NULL,
    nom character varying(100) NOT NULL,
    joc character varying(100) NOT NULL,
    partida integer,
    competitiu boolean NOT NULL,
    usuari_organitzador integer,
    resultat integer,
    virtual boolean NOT NULL,
    format integer,
    premi text,
    data_d_inici date NOT NULL,
    data_final date
);


ALTER TABLE public.torneig OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16431)
-- Name: torneig_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.torneig_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.torneig_id_seq OWNER TO postgres;

--
-- TOC entry 3485 (class 0 OID 0)
-- Dependencies: 226
-- Name: torneig_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.torneig_id_seq OWNED BY public.torneig.id;


--
-- TOC entry 227 (class 1259 OID 16432)
-- Name: usuaris; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaris (
    id integer NOT NULL,
    rol integer,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    bio text,
    telefono character varying(20),
    contrasenya character varying(255) NOT NULL,
    subscripcio integer,
    estadistiques integer,
    rang integer,
    data_de_registre timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.usuaris OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16438)
-- Name: usuaris_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuaris_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuaris_id_seq OWNER TO postgres;

--
-- TOC entry 3486 (class 0 OID 0)
-- Dependencies: 228
-- Name: usuaris_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuaris_id_seq OWNED BY public.usuaris.id;


--
-- TOC entry 3262 (class 2604 OID 16439)
-- Name: emparellaments id_emparellant; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emparellaments ALTER COLUMN id_emparellant SET DEFAULT nextval('public.emparellaments_id_emparellant_seq'::regclass);


--
-- TOC entry 3266 (class 2604 OID 16440)
-- Name: estadistiques id_estats; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadistiques ALTER COLUMN id_estats SET DEFAULT nextval('public.estadistiques_id_estats_seq'::regclass);


--
-- TOC entry 3267 (class 2604 OID 16441)
-- Name: format id_format; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.format ALTER COLUMN id_format SET DEFAULT nextval('public.format_id_format_seq'::regclass);


--
-- TOC entry 3268 (class 2604 OID 16442)
-- Name: partida id_partida; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida ALTER COLUMN id_partida SET DEFAULT nextval('public.partida_id_partida_seq'::regclass);


--
-- TOC entry 3269 (class 2604 OID 16443)
-- Name: rang id_rang; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rang ALTER COLUMN id_rang SET DEFAULT nextval('public.rang_id_rang_seq'::regclass);


--
-- TOC entry 3270 (class 2604 OID 16444)
-- Name: resultat id_resultat; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resultat ALTER COLUMN id_resultat SET DEFAULT nextval('public.resultat_id_resultat_seq'::regclass);


--
-- TOC entry 3271 (class 2604 OID 16445)
-- Name: rol id_rol; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol ALTER COLUMN id_rol SET DEFAULT nextval('public.rol_id_rol_seq'::regclass);


--
-- TOC entry 3272 (class 2604 OID 16446)
-- Name: subscripcio id_subscripcio; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscripcio ALTER COLUMN id_subscripcio SET DEFAULT nextval('public.subscripcio_id_subscripcio_seq'::regclass);


--
-- TOC entry 3273 (class 2604 OID 16447)
-- Name: torneig id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig ALTER COLUMN id SET DEFAULT nextval('public.torneig_id_seq'::regclass);


--
-- TOC entry 3275 (class 2604 OID 16448)
-- Name: usuaris id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris ALTER COLUMN id SET DEFAULT nextval('public.usuaris_id_seq'::regclass);


--
-- TOC entry 3450 (class 0 OID 16385)
-- Dependencies: 209
-- Data for Name: emparellaments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.emparellaments (id_emparellant, id_usuari1, id_usuari2) FROM stdin;
\.


--
-- TOC entry 3452 (class 0 OID 16389)
-- Dependencies: 211
-- Data for Name: estadistiques; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estadistiques (id_estats, partides_jugades, partides_guanyades, punts_totals) FROM stdin;
\.


--
-- TOC entry 3454 (class 0 OID 16396)
-- Dependencies: 213
-- Data for Name: format; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.format (id_format, nom, joc, jugadors, temps, regles) FROM stdin;
\.


--
-- TOC entry 3456 (class 0 OID 16402)
-- Dependencies: 215
-- Data for Name: partida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partida (id_partida, data_inici, estat, id_emparellant) FROM stdin;
\.


--
-- TOC entry 3458 (class 0 OID 16406)
-- Dependencies: 217
-- Data for Name: rang; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rang (id_rang, nom, descripcio) FROM stdin;
\.


--
-- TOC entry 3460 (class 0 OID 16412)
-- Dependencies: 219
-- Data for Name: resultat; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.resultat (id_resultat, joc, resultat) FROM stdin;
\.


--
-- TOC entry 3462 (class 0 OID 16418)
-- Dependencies: 221
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id_rol, nom, permet_torneig) FROM stdin;
\.


--
-- TOC entry 3464 (class 0 OID 16422)
-- Dependencies: 223
-- Data for Name: subscripcio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscripcio (id_subscripcio, data_inici, data_final, tipus, estat) FROM stdin;
\.


--
-- TOC entry 3466 (class 0 OID 16426)
-- Dependencies: 225
-- Data for Name: torneig; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.torneig (id, nom, joc, partida, competitiu, usuari_organitzador, resultat, virtual, format, premi, data_d_inici, data_final) FROM stdin;
\.


--
-- TOC entry 3468 (class 0 OID 16432)
-- Dependencies: 227
-- Data for Name: usuaris; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuaris (id, rol, username, email, bio, telefono, contrasenya, subscripcio, estadistiques, rang, data_de_registre) FROM stdin;
\.


--
-- TOC entry 3487 (class 0 OID 0)
-- Dependencies: 210
-- Name: emparellaments_id_emparellant_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.emparellaments_id_emparellant_seq', 1, false);


--
-- TOC entry 3488 (class 0 OID 0)
-- Dependencies: 212
-- Name: estadistiques_id_estats_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estadistiques_id_estats_seq', 1, false);


--
-- TOC entry 3489 (class 0 OID 0)
-- Dependencies: 214
-- Name: format_id_format_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.format_id_format_seq', 1, false);


--
-- TOC entry 3490 (class 0 OID 0)
-- Dependencies: 216
-- Name: partida_id_partida_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partida_id_partida_seq', 1, false);


--
-- TOC entry 3491 (class 0 OID 0)
-- Dependencies: 218
-- Name: rang_id_rang_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rang_id_rang_seq', 1, false);


--
-- TOC entry 3492 (class 0 OID 0)
-- Dependencies: 220
-- Name: resultat_id_resultat_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.resultat_id_resultat_seq', 1, false);


--
-- TOC entry 3493 (class 0 OID 0)
-- Dependencies: 222
-- Name: rol_id_rol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_rol_seq', 1, false);


--
-- TOC entry 3494 (class 0 OID 0)
-- Dependencies: 224
-- Name: subscripcio_id_subscripcio_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscripcio_id_subscripcio_seq', 1, false);


--
-- TOC entry 3495 (class 0 OID 0)
-- Dependencies: 226
-- Name: torneig_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.torneig_id_seq', 1, false);


--
-- TOC entry 3496 (class 0 OID 0)
-- Dependencies: 228
-- Name: usuaris_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuaris_id_seq', 1, false);


--
-- TOC entry 3277 (class 2606 OID 16450)
-- Name: emparellaments emparellaments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emparellaments
    ADD CONSTRAINT emparellaments_pkey PRIMARY KEY (id_emparellant);


--
-- TOC entry 3279 (class 2606 OID 16452)
-- Name: estadistiques estadistiques_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estadistiques
    ADD CONSTRAINT estadistiques_pkey PRIMARY KEY (id_estats);


--
-- TOC entry 3281 (class 2606 OID 16454)
-- Name: format format_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.format
    ADD CONSTRAINT format_pkey PRIMARY KEY (id_format);


--
-- TOC entry 3283 (class 2606 OID 16456)
-- Name: partida partida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT partida_pkey PRIMARY KEY (id_partida);


--
-- TOC entry 3285 (class 2606 OID 16458)
-- Name: rang rang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rang
    ADD CONSTRAINT rang_pkey PRIMARY KEY (id_rang);


--
-- TOC entry 3287 (class 2606 OID 16460)
-- Name: resultat resultat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resultat
    ADD CONSTRAINT resultat_pkey PRIMARY KEY (id_resultat);


--
-- TOC entry 3289 (class 2606 OID 16462)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id_rol);


--
-- TOC entry 3291 (class 2606 OID 16464)
-- Name: subscripcio subscripcio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscripcio
    ADD CONSTRAINT subscripcio_pkey PRIMARY KEY (id_subscripcio);


--
-- TOC entry 3293 (class 2606 OID 16466)
-- Name: torneig torneig_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig
    ADD CONSTRAINT torneig_pkey PRIMARY KEY (id);


--
-- TOC entry 3295 (class 2606 OID 16468)
-- Name: usuaris usuaris_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_email_key UNIQUE (email);


--
-- TOC entry 3297 (class 2606 OID 16470)
-- Name: usuaris usuaris_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_pkey PRIMARY KEY (id);


--
-- TOC entry 3299 (class 2606 OID 16472)
-- Name: usuaris usuaris_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_username_key UNIQUE (username);


--
-- TOC entry 3300 (class 2606 OID 16473)
-- Name: emparellaments emparellaments_id_usuari1_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emparellaments
    ADD CONSTRAINT emparellaments_id_usuari1_fkey FOREIGN KEY (id_usuari1) REFERENCES public.usuaris(id);


--
-- TOC entry 3301 (class 2606 OID 16478)
-- Name: emparellaments emparellaments_id_usuari2_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.emparellaments
    ADD CONSTRAINT emparellaments_id_usuari2_fkey FOREIGN KEY (id_usuari2) REFERENCES public.usuaris(id);


--
-- TOC entry 3303 (class 2606 OID 16483)
-- Name: torneig fk_format; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig
    ADD CONSTRAINT fk_format FOREIGN KEY (format) REFERENCES public.format(id_format);


--
-- TOC entry 3304 (class 2606 OID 16488)
-- Name: torneig fk_partida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig
    ADD CONSTRAINT fk_partida FOREIGN KEY (partida) REFERENCES public.partida(id_partida);


--
-- TOC entry 3302 (class 2606 OID 16493)
-- Name: partida partida_id_emparellant_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT partida_id_emparellant_fkey FOREIGN KEY (id_emparellant) REFERENCES public.emparellaments(id_emparellant);


--
-- TOC entry 3305 (class 2606 OID 16498)
-- Name: torneig torneig_resultat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig
    ADD CONSTRAINT torneig_resultat_fkey FOREIGN KEY (resultat) REFERENCES public.resultat(id_resultat);


--
-- TOC entry 3306 (class 2606 OID 16503)
-- Name: torneig torneig_usuari_organitzador_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.torneig
    ADD CONSTRAINT torneig_usuari_organitzador_fkey FOREIGN KEY (usuari_organitzador) REFERENCES public.usuaris(id);


--
-- TOC entry 3307 (class 2606 OID 16508)
-- Name: usuaris usuaris_estadistiques_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_estadistiques_fkey FOREIGN KEY (estadistiques) REFERENCES public.estadistiques(id_estats);


--
-- TOC entry 3308 (class 2606 OID 16513)
-- Name: usuaris usuaris_rang_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_rang_fkey FOREIGN KEY (rang) REFERENCES public.rang(id_rang);


--
-- TOC entry 3309 (class 2606 OID 16518)
-- Name: usuaris usuaris_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_rol_fkey FOREIGN KEY (rol) REFERENCES public.rol(id_rol);


--
-- TOC entry 3310 (class 2606 OID 16523)
-- Name: usuaris usuaris_subscripcio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaris
    ADD CONSTRAINT usuaris_subscripcio_fkey FOREIGN KEY (subscripcio) REFERENCES public.subscripcio(id_subscripcio);


--
-- TOC entry 3476 (class 0 OID 0)
-- Dependencies: 3475
-- Name: DATABASE turnonauta; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE turnonauta TO turnonauta;


-- Completed on 2025-02-26 15:55:11 CET

--
-- PostgreSQL database dump complete
--

-- Completed on 2025-02-26 15:55:11 CET

--
-- PostgreSQL database cluster dump complete
--
